config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'documents#index'
  resources :documents, only: [:show, :edit, :update]
  get '/documents' => redirect('/')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :integer          not null, primary key
#  name       :string
#  domain     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Company < ApplicationRecord
  validates :name, presence: true
  validates :domain, presence: true
end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id         :integer          not null, primary key
#  company_id :integer
#  name       :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Document < ApplicationRecord
  belongs_to :company

  validates :name, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # e.g. with email 'sue@spacex.com', will return 'spacex.com'
  def domain
    # email will equal sue@spacex.com
    # => spacex.com
    self.email.split('@').last
  end

  def company
    Company.find_by(domain: self.domain)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  private
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update]
  
  def index
    if signed_in?
      company = current_user.company
      @documents = Document.where(company: company)
    end
  end

  def show
  end

  def edit
  end

  def update
    if @document.update(document_params)
      # Success, get to #show page
      redirect_to @document
    else
      # Error, render edit form again
      render :edit
    end
  end

  private
    # What attributes we allow from forms
    def document_params
      params.require(:document).permit(:name, :content)
    end

    # Get document id and check document policy
    def set_document
      @document = Document.find(params[:id])
      authorize @document
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/application/_user_info.html.erb
<% if signed_in? %>
  <div>
    <dl>
      <dt>Email</dt>
      <dd><%= current_user.email %></dd>
      <dt>Domain</dt>
      <dd><%= current_user.domain %></dd>
      <dt>Company</dt>
      <dd><%= current_user.company.name %></dd>
    </dl>

    <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
  </div>
<% else %>
  <div>
    <%= link_to 'Sign in', new_user_session_path %>
  </div>
<% end %>

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |f| %>
  <div class="form-control">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-control">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <%= f.button %>
<% end %>

app/views/documents/edit.html.erb
<h1>Edit Document</h1> 

<%= render 'form', document: @document %>

<%= link_to 'Back', @document %>

app/views/documents/index.html.erb
<h1>Top Secret Documents</h1>

<% if signed_in? %>
  <% @documents.each do |document| %>
    <h2><%= link_to document.name, document %></h2>
    <h3><%= document.company.name %></h3>
  <% end %>
<% end %>

app/views/documents/show.html.erb
<h1><%= @document.name %></h1>
<p><%= @document.content %></p>

<% if policy(@document).edit? %>
  <%= link_to 'Edit', edit_document_path(@document) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TopSecret</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'user_info' %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>